#! /bin/sh

## set up the two monitors
## NOTE This is a simplistic approach because I already know the settings I
## want to apply.
my_laptop_external_monitor=$(xrandr --query | grep -ow 'DP-1 connected')
if [[ $my_laptop_external_monitor = *connected* ]]; then
	xrandr --output DP-1 --primary --mode 3440x1440 --rate 100 --output eDP-1 --off &
else
	xrandr --output eDP-1 --mode 1920x1200 --rate 60 &
fi

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

# Toggle keyboard layouts
setxkbmap -option grp:win_space_toggle us,es &

# Restore wallpaper
nitrogen --restore &

nm-applet &

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/bspwm/polybar/launch.sh

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' '漣'
		let name++
	done
}
workspaces

bspc config border_width 3
bspc config window_gap 10
bspc config split_ratio 0.50
# bspc config top_padding 0
# bcpc config bottom_padding 0

bspc config focused_border_color '#31748f'
bspc config normal_border_color '#2E2B46'
bspc config active_border_color '#2E2B46'
bspc config presel_feedback_color '#2E2B46'

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# fix pointer
xsetroot -cursor_name left_ptr

# State rules for specific apps
bspc rule -a Zathura state=tiled
bspc rule -a Nitrogen state=floating

# workspace 4 (Settings)
declare -a settings=(Pavucontrol Xfce4-settings-manager blueberry)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^4' follow=on focus=on; done

## Autostart

# Kill if already running
killall -9 picom sxhkd dunst xfce4-power-manager 

# Launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi

# Launch keybindings daemon
sxhkd &

# Enable power management
xfce4-power-manager &

# Start udiskie
udiskie &

$HOME/.config/bspwm/scripts/bspcomp &
$HOME/.config/bspwm/scripts/bspbar &
$HOME/.config/bspwm/scripts/bspfloat
