## Configuration for Alacritty, the GPU enhanced terminal emulator.

## It's a very basic and simple config file, for full configuration...
## See, /usr/share/doc/alacritty/example/alacritty.yml

## Import files (Colors, Fonts, Etc)
import:
  - ~/.config/alacritty/colors.yml
  - ~/.config/alacritty/fonts.yml

## Set environment variables
env:
  TERM: xterm-256color
  WINIT_X11_SCALE_FACTOR: '1.0'

## Terminal window settings
window:
  dimensions:
    columns: 180
    lines: 55

  padding:
    x: 12
    y: 12

  decorations: Full
  startup_mode: Windowed
  dynamic_title: true
  option_as_alt: Both

## scrolling
  history: 10000
  multiplier: 3

## Background opacity
  opacity: 1.0 

## Cursor
cursor:
  style:
    shape: Block
    blinking: On

  unfocused_hollow: false

## Live config reload
live_config_reload: true

