# ┬─┐┌─┐┌─┐┌─┐  ┌─┐┬┌┐┌┌─┐
# ├┬┘│ │└─┐├┤   ├─┘││││├┤ 
# ┴└─└─┘└─┘└─┘  ┴  ┴┘└┘└─┘

colors:
  # Default colors
  primary:
    background: '#191724'
    foreground: '#e0def4'

  # Normal colors
  normal:
    black:   '#6e6a86'
    red:     '#eb6f92'
    green:   '#9ccfd8'
    yellow:  '#f6c177'
    blue:    '#31748f'
    magenta: '#c4a7e7'
    cyan:    '#ebbcba'
    white:   '#e0def4'

  # Bright colors
  bright:
    black:   '#6e6a86'
    red:     '#eb6f92'
    green:   '#9ccfd8'
    yellow:  '#f6c177'
    blue:    '#31748f'
    magenta: '#c4a7e7'
    cyan:    '#ebbcba'
    white:   '#e0def4'
